config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :index, :show, :dashboard, :edit] do
    get 'update_profile', to: 'users#update_profile'
    get 'dashboard', to: 'users#dashboard'
    get 'add_skill', to: 'users#add_skill'
  end
  root to: 'pages#home'
  resources :skills, only: [ :index ]
  resources :work_sessions, only: [ :new, :edit, :update, :show, :create ] do
    resources :reviews, only: [:new, :create]
    member do
      post 'validate'
      post 'decline'
      post 'done'
    end
    resources :messages, only: [ :new, :create, :show ] do
      collection do
        get 'type'
      end
    end
  end


end

app/models/work_session.rb
class WorkSession < ApplicationRecord
  belongs_to :problem_user, :class_name => 'User', :foreign_key => 'problem_user_id'
  belongs_to :solver_user, :class_name => 'User', :foreign_key => 'solver_user_id'
  has_many :messages, dependent: :nullify
  validates :starts_at, presence: true
  validates :brief, presence: true
end

app/controllers/work_sessions_controller.rb
class WorkSessionsController < ApplicationController
  before_action :set_work_session, only: [ :show, :edit, :update, :validate, :decline, :done ]

  def show
    @message = Message.new
    @review = Review.new
    @conversation = Message.where(work_session_id: @work_session.id)
    authorize @work_session
  end

  def new
    @work_session = WorkSession.new
    @user = User.new
    authorize @work_session
    parameters = params[:skill][:name]
    index_of_separator = parameters.each_index.select{|i| parameters[i] == ""}.pop
    main_skills =  []
    other_skills = []

    params[:skill][:name].each_with_index do |skill, index|
      if index_of_separator.zero?
          main_skills << skill unless skill.empty?
      else
        unless skill.empty?
          index < index_of_separator ? main_skills << skill : other_skills << skill
        end
      end
    end
    users_with_main_skills = policy_scope(User).tagged_with(main_skills, :any => true)

    #TODO Need to check how to filter users with main skills and optional skills without duplicates users
    user_with_optional_skills = policy_scope(User).tagged_with(other_skills, :any => true)

    # We sort users by descending order depending on their number of skills
    @users = users_with_main_skills.sort_by { |user| user.tag_list.length}.reverse

    @users.include?(current_user) ? @users.delete(current_user) :  @users
  end

  def create
    @solver_user = User.find(params[:work_session][:solver_user_id])
    @problem_user = current_user
    @work_session = WorkSession.new(work_session_params)
    @work_session.problem_user = @problem_user
    @work_session.solver_user = @solver_user
    authorize @work_session
    if @work_session.save
      redirect_to work_session_path(@work_session)
    else
      render :new
    end
  end

  def edit
    authorize @work_session
  end

  def update
    authorize @work_session
    if @work_session.update
      redirect_to @work_session
    else
      render :edit
    end
  end

  def validate
    authorize @work_session
    @work_session.update(status: "validate")
    redirect_to work_session_path(@work_session)
  end

  def decline
    authorize @work_session
    @work_session.update(status: "decline")
    redirect_to work_session_path(@work_session)
  end

  def done
    authorize @work_session
    @work_session.update(status: "done")
    @solver_user = @work_session.solver_user
    @solver_user.points += 50
    @solver_user.save
    redirect_to work_session_path(@work_session)
  end

  private

  def set_work_session
    @work_session = WorkSession.find(params[:id])
  end

  def work_session_params
    params.require(:work_session).permit(:solver_user_id, :problem_user_id, :brief, :starts_at, :status)
  end
end

app/views/work_sessions/_chat.html.erb
<div id="chat">
 <div id="chat-content" class="<%= current_user.id %>">
  <div class="<%= @work_session.problem_user == current_user ? 'message_from_current_user current_user' : 'message_from_other_user other_user' %>">
       <p class="username"> <%= @work_session.problem_user.first_name %> </p>
       <p class="message_text"> Hey <%= @work_session.solver_user.first_name %>! I need your help, are you available on <%= l(@work_session.starts_at, format: '%A %e %B') %>?</p>
     </div>
   <% @conversation.each do |message| %>
   <div class="<%= message.user == current_user ? 'message_from_current_user current_user' : 'message_from_other_user other_user' %>">
     <p class="username"> <%= message.user.first_name %> </p>
     <p class="message_text"> <%= message.content %> </p>
   </div>
   <% end %>
 </div>
 <div class="brief text-center">
   <%= render partial: 'messages/message_form', locals: {message: @message, work_session: @work_session}%>
 </div>
 </div>

app/views/work_sessions/edit.html.erb
<h1>edit work session</h1>

app/views/work_sessions/new.html.erb
<div class="progress-session">
  <div class="progress-nav">
    <div class="step active" id="step-one">
      <div>1</div>
      <h3>Choose a buddy</h3>
    </div>
    <div class="dash"></div>
    <div class="step" id="step-two">
      <div>2</div>
      <h3>Set a brief</h3>
    </div>
    <div class="dash"></div>
    <div class="step" id="step-three">
      <div>3</div>
      <h3>Pick a date</h3>
    </div>
  </div>

  <div class="progress-body">
    <%= simple_form_for @work_session do |f| %>
    <div id='user-index'>
      <%= render 'users/index' %>
      <% @users.each do |user| %>
        <%= render "users/user_card", user: user %>
      <% end %>
      <%= f.hidden_field :solver_user_id, id: 'solver_id' %>
    </div>

    <div class="hidden" id='brief'>
      <h3 class="text-center">Write your Brief</h3>
      <div class="brief text-center">
        <%= f.input :brief, as: :text, label: false, input_html: { id: 'brief-editor' } %>
        <%= link_to "Send Brief", "", class: 'btn btn-primary send-brief' %>
      </div>
    </div>

    <div class="hidden" id='datepicker'>

      <div class="datepicker-container">
        <h3>Enter a meeting date</h3>

        <div class="datepicker-input">
          <%= f.input_field :starts_at, placeholder: "Sat 7th November", :class => 'datepicker form-control', as: :string %>
          <%= f.submit class: "btn btn-success" %>
        </div>
      </div>

    </div>
    <% end %>

  </div>
</div>

app/views/work_sessions/show.html.erb
<div class="working-space container">
  <div class="left-part">
    <div class="header text-center">
      <% if @work_session.problem_user.linkedin_picture_url.nil? %>
        <% if @work_session.problem_user.photo.nil? %>
          <%= image_tag "profile_default.png", class: "img-circle" %>
        <% else %>
          <%= cl_image_tag(@work_session.problem_user.photo.path, width: 50, height: 50, crop: :fill, class: "img-circle") %>
        <%end%>
      <% else %>
          <%= image_tag(@work_session.problem_user.linkedin_picture_url, class: "img-circle") %>
      <% end %>

      <% if @work_session.solver_user.linkedin_picture_url.nil? %>
        <% if @work_session.solver_user.photo.nil? %>
          <%= image_tag "profile_default.png", class: "img-circle" %>
        <% else %>
          <%= cl_image_tag(@work_session.solver_user.photo.path, width: 50, height: 50, crop: :fill, class: "img-circle") %>
        <%end%>
      <% else %>
          <%= image_tag @work_session.solver_user.linkedin_picture_url, class: "img-circle" %>
      <% end %>


      <h2><%= @work_session.starts_at.strftime("%A %e %B %Y") %></h2>
      <p><%= @work_session.status.capitalize %></p>

      <div class="points">
        <p>to win: <%= pluralize(50, "point") %> <i class="fa fa-star"></i></p>
      </div>
      <div class="work_session_buttons">
        <% if current_user.id == @work_session.solver_user_id %>
          <% if @work_session.status == "pending" %>
            <%= link_to "Validate", validate_work_session_path(@work_session), class: "btn btn-success btn-work-session1", method: :post %>
            <%= link_to "Decline", decline_work_session_path(@work_session), class: "btn btn-danger btn-work-session2", method: :post %>
          <% end %>
        <% elsif current_user.id == @work_session.problem_user_id %>
          <% if @work_session.status == "validate" %>
            <%= link_to "Done", done_work_session_path(@work_session), class: "btn btn-warning btn-work-session1", method: :post %>
          <% elsif @work_session.status == "done" %>
            <%= button_tag "Add a review", type: 'button', data: { target: "#newReview", toggle: "modal"}, class: "btn btn-primary btn-work-session1" %>
          <% end %>
        <% end %>
      </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="newReview" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= image_tag 'like.png', class: 'center-block' %>
        <h4 class="modal-title text-center" id="myModalLabel">Write your review</h4>
      </div>
      <div class="modal-body">
        <%= render 'reviews/new', work_session: @work_session, review: @review %>
      </div>
    </div>
  </div>
</div>

    <div class="body">
      <div class="files-box">
        <div class="file-box" id="files">
          <%#= image_tag "xls.png" %>
          <!-- <p>spreadsheet.xls</p>-->
        </div>
        <div class="file-box">
          <%#= image_tag "pdf.png" %>
         <!--  <p>brief.pdf</p> -->
        </div>
      </div>
      <div class="brief-text">
        <%= @work_session.brief.html_safe %>
      </div>
    </div>

  </div>

  <div class="right-part">
    <%= render 'chat', work_session: @work_session, message: @message %>
  </div>
</div>




<%= content_for(:after_js) do %>
  <script>
  $('#new_message').keyup(function(e) {
    var key = e.which;
    if (key == 13) {
      // As ASCII code for ENTER key is "13"
      $('#new_message').submit(); // Submit form code
    }
    $.ajax({
      type: "GET",
      url: "<%= type_work_session_messages_path(@work_session) %>" + "?content=" + $('#message_content').val()
    })
  });


  // $('#new_message').on('click', function() {
  //   $('#message_sent_sound').play();
  // });

  </script>
<% end %>