config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [ :index, :show, :dashboard, :edit] do
    get 'update_profile', to: 'users#update_profile'
    get 'dashboard', to: 'users#dashboard'
    get 'add_skill', to: 'users#add_skill'
  end
  root to: 'pages#home'
  resources :skills, only: [ :index ]
  resources :work_sessions, only: [ :new, :edit, :update, :show, :create ] do
    resources :reviews, only: [:new, :create]
    member do
      post 'validate'
      post 'decline'
      post 'done'
    end
    resources :messages, only: [ :new, :create, :show ] do
      collection do
        get 'type'
      end
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :problem_user, :class_name => 'User', :foreign_key => 'problem_user_id'
  belongs_to :solver_user, :class_name => 'User', :foreign_key => 'solver_user_id'
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :work_session
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :work_session
end

app/models/skill.rb
class Skill < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:linkedin]
  acts_as_taggable_on :tags
  has_many :messages, through: :work_sessions
  has_many :problems, :class_name => 'WorkSession', :foreign_key => 'problem_user_id'
  has_many :askings, :class_name => 'WorkSession', :foreign_key => 'solver_user_id'
  has_attachment :photo
  def self.find_for_linkedin_oauth(auth)
    #TODO Add
    user_params = auth.to_h.slice(:uid, :provider)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:linkedin_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    # user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
     user.update(user_params)
    else
     user = User.new(user_params)
     user.password = Devise.friendly_token[0,20]  # Fake password for validation
     user.save
    end

    return user
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/work_session.rb
class WorkSession < ApplicationRecord
  belongs_to :problem_user, :class_name => 'User', :foreign_key => 'problem_user_id'
  belongs_to :solver_user, :class_name => 'User', :foreign_key => 'solver_user_id'
  has_many :messages, dependent: :nullify
  validates :starts_at, presence: true
  validates :brief, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @skill = Skill.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    #TODO Add a good filter to have users who work_session the main skills and the optional skills, now we just have the main skills
    @work_session = WorkSession.new
    @user = User.new
    parameters = params[:skill][:name]
    index_of_separator = parameters.each_index.select{|i| parameters[i] == ""}.pop
    main_skills =  []
    other_skills = []
    skills = other_skills.empty? ? main_skills : main_skills + other_skills

    params[:skill][:name].each_with_index do |skill, index|
      if index_of_separator.zero?
          main_skills << skill unless skill.empty?
      else
        unless skill.empty?
          index < index_of_separator ? main_skills << skill : other_skills << skill
        end
      end
    end
    users_with_main_skills = policy_scope(User).tagged_with(main_skills, :any => true)

    #TODO Need to check how to filter users with main skills and optional skills without duplicates users
    user_with_optional_skills = policy_scope(User).tagged_with(other_skills, :any => true)

    @users = policy_scope(User).tagged_with(main_skills).to_a

    @users.include?(current_user) ? @users.delete(current_user) :  @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def dashboard
    @skills = current_user.tag_list
    @user = current_user
    @sessions = WorkSession.where(solver_user: @user)
    @kombos = @sessions.or(WorkSession.where(problem_user: @user))
    authorize @user
  end


  def edit
    @user = current_user(user_params)
    authorize @user
  end

  def update_profile
    @user = current_user(user_params)
    @user.update
    authorize @user
  end

def add_skill
  @sessions = WorkSession.where(current_user.id == params[:solver_user_id])
  @skills = current_user.tag_list
  @user = current_user
  skill = params[:skill][:name].reject{|skill| skill.blank?}
  @user.tag_list.add(skill)
  @kombos = @sessions.or(WorkSession.where(problem_user: @user))
  authorize @user

  if @user.save
    render :dashboard
  end
end

private
def user_params
params.require(:user).permit(:first_name, :last_name, :work_department, :profile_description, :photo)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

  def current_user?
    message.user == current_user ? "message_from_current_user" : "message_from_other_user"
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-default <%= params[:action] == 'home' ? 'navbar-home' : '' %>">
    <div class="container-fluid">
      <div class="navbar-brand">
        <%= link_to image_tag("logotrans.png", width: 60, :class => "logo"), root_path %>
      </div>

      <% if user_signed_in? %>
        <ul class=" myul nav navbar-nav navbar-right">

          <!-- <li class="navelement">
            <%= link_to "#" do %>
              <div class="whole_badge">
                <i class="fa fa-envelope-o"></i>
                <div class="badge badge-blue">3</div>
              </div>
            <% end %>
            <span class="span"></span>
          </li> -->

          <% if current_user.linkedin_picture_url.nil? %>
            <% if current_user.photo.nil? %>
              <%= link_to edit_user_registration_path do %>
                <%= image_tag "profile_default.png", class: "avatar", style: "margin-left: 20px;" %>
              <% end %>
            <% else %>
                <%= link_to edit_user_registration_path do %>
                  <%= cl_image_tag current_user.photo.path, width: 30, height: 30, crop: :fill, class: "avatar", style: "margin-left: 20px;" %>
                <%end%>
            <% end %>
          <% else %>
            <%= link_to edit_user_registration_path do %>
              <%= image_tag current_user.linkedin_picture_url, class: "avatar", style: "margin-left: 20px;" %>
            <% end %>
          <% end %>

          <li class="navelement"> <%= link_to "Dashboard", user_dashboard_path(current_user) %>
            <span class="span"></span>
          </li>
          <li class="navelement"> <%= link_to "Sign out", destroy_user_session_path, method: :delete %>  <span class="span"></span class="span"></li>
        </ul>

      <% else %>
        <ul class="myul nav navbar-nav navbar-right">
          <li class="navelement"><%= link_to "Sign up", new_user_registration_path %>
            <span class="span"></span>
          </li>
          <li class="navelement"><%= link_to "Log in", new_user_session_path %>  <span class="span"></span> </li>
        </ul>
      <% end %>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag "favicon.ico" %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="keywords" content="work, pair, teamwork, collaboration, efficiency, mutual learning">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body class="<%= params[:action] == 'home' ? '' : 'padded' %>">
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Flip/1.1.2/jquery.flip.min.js">
</script>
    <%= cloudinary_js_config %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag "application-print", :media => "print" %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= asset_url('workingduo.jpg') %>);">


  <div class="banner-content">
    <div class="box">

    <div class="box-head">
      <h1 style="opacity:1;"><span style="color: #FF895D">Stuck </span> on something?</h1>
      <p style="font-size: 23px; color:white;"> Find a collegue with the skills you <span style="color: #FF895D"><strong> need! </strong></span> </p>
      <!-- <h3>Main skills</h3> -->
      <%= simple_form_for :skill, method: "get", url: new_work_session_path do |f| %>
      <%= f.input :name, label: false, as: :select, collection: Skill.all.map { |skill| [skill.name, skill.name] }, input_html: { rows: 6, class: "chosen-select", multiple: true, :data => { :placeholder => 'select the skills you need '}} %>
      <!-- <h3> Optional skills </h3>
      <%= f.input :name, label: false, as: :select, collection: Skill.all.map { |skill| [skill.name, skill.name] }, input_html: { rows: 6, class: "chosen-select", multiple: true, :data => { :placeholder => 'Select the skills you need '}} %>
   -->
    </div>
    <%= f.submit "See buddies", class: "btn-mine box-footer" %>

    <% end %>
  </div>
</div>
</div>

<% if user_signed_in? %>
<% else %>
  <div class="row">
    <div class="box">
      <h3 style="text-align:center;" class="js-shadow" id="myh2"> How Kombo is working?</h3>
    </div>
  </div>

  <div class="description">
    <div class="container-fluid">
      <div class="row">

        <div class="icones-container">
          <div class="col-md-4">
            <h4 style="text-align:center;" class=> Categorize your need</h4>
            <div class="icones" id="icone1"></div>
          </div>

        <div class="col-md-4">
          <h4 style="text-align:center;">find the good one </h4>
          <div class="icones" id="icone2"></div>
        </div>


        <div class="col-md-4">
          <h4 style="text-align:center;">work in pair</h4>
          <div class="icones" id="icone3"></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "<%= current_user.linkedin_picture_url %>", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>